kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-adityadixithwk5
  labels:
      region: eu-de
      zone: fra02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-block-5iops-tier
  