apiVersion: batch/v1
kind: Job
metadata:
  name: trainjob-adityadixithwk5
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: trainjob-adityadixithwk5
        image: adidix/train
        command: ["python3", "train.py"]
        volumeMounts:
        - name: volumehwk5
          mountPath: /models
      restartPolicy: Never
      volumes:
        - name: volumehwk5
          persistentVolumeClaim:
            claimName: pvc-adityadixithwk5
